// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDINy6ZIkmU8Lqf608Z4P7nNyjmpo_aNz0',
    appId: '1:249548218947:web:4b8c6de754a9caf5db2af6',
    messagingSenderId: '249548218947',
    projectId: 'chat-app-b2ee2',
    authDomain: 'chat-app-b2ee2.firebaseapp.com',
    storageBucket: 'chat-app-b2ee2.firebasestorage.app',
    measurementId: 'G-BCBBR3PV8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkKCzBPeiwwYrZCHsSc36BWp0ZFjIMBXY',
    appId: '1:249548218947:android:45128f350d707d9adb2af6',
    messagingSenderId: '249548218947',
    projectId: 'chat-app-b2ee2',
    storageBucket: 'chat-app-b2ee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1dhdYn7GDt6EB6Hj0jGb_kgbSdl-4oHA',
    appId: '1:249548218947:ios:a0c02751abafdfa0db2af6',
    messagingSenderId: '249548218947',
    projectId: 'chat-app-b2ee2',
    storageBucket: 'chat-app-b2ee2.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1dhdYn7GDt6EB6Hj0jGb_kgbSdl-4oHA',
    appId: '1:249548218947:ios:a0c02751abafdfa0db2af6',
    messagingSenderId: '249548218947',
    projectId: 'chat-app-b2ee2',
    storageBucket: 'chat-app-b2ee2.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDINy6ZIkmU8Lqf608Z4P7nNyjmpo_aNz0',
    appId: '1:249548218947:web:f7f4dedb02106c72db2af6',
    messagingSenderId: '249548218947',
    projectId: 'chat-app-b2ee2',
    authDomain: 'chat-app-b2ee2.firebaseapp.com',
    storageBucket: 'chat-app-b2ee2.firebasestorage.app',
    measurementId: 'G-CBGD6V3357',
  );
}
